/**
 * Writes production environment from NG_APP_API_URL (Vercel env vars).
 * Usage: node scripts/set-env.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'src', 'environments', 'environment.production.ts');

const apiBaseUrl = (process.env.NG_APP_API_URL || process.env.API_BASE_URL || '').replace(/\/$/, '');

const content = `/**
 * Auto-generated by scripts/set-env.mjs — do not edit by hand on CI.
 * NG_APP_API_URL=${apiBaseUrl || '(empty = same-origin /api proxy)'}
 */
export const environment = {
  production: true,
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)}
};
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, content, 'utf8');
console.log(`[set-env] apiBaseUrl = ${apiBaseUrl || '(empty)'}`);
